### PR TITLE
Change Makefile to use standard docker build method

### PR DESCRIPTION
**Pull request by hyunsun**

### CODE REVIEW

**Comment by krsna1729** [comment]
@hyunsun missed dockerfile ;)

**Comment by hyunsun** [comment]
It doesn't need any changes on Dockerfile :)

**Comment by krsna1729** [comment]
@hyunsun ooh nice `--label`. Can we do this to other repos too?

**Comment by hyunsun** [comment]
@krsna1729 sure

**Review by krsna1729 — APPROVED** [review]
builds. @pingping-lin please take a look and merge

**Comment by hyunsun** [comment]
@pingping-lin @zdw please review

**Review by zdw — APPROVED** [review]
Looks good. It looks like TC1 is failing - is this unrelated?

**Comment by hyunsun** [comment]
I think it is unrelated as this PR does not touch any source codes.

**Comment by krsna1729** [comment]
TC1 failure is unrelated to this patch. LGTM

**Comment by hyunsun** [comment]
@zdw Could you merge this? @pingping-lin seems have a problem with her github account.

**Comment by zdw** [comment]
> @zdw Could you merge this? @pingping-lin seems have a problem with her github account.

Any reason why Jenkins is failing this?  Is there something wrong with the job?

I'm hesitant to approve and merge patchsets where the tests are broken.

**Comment by hyunsun** [comment]
@zdw No idea. TC1 has not been working for about a month. I left a question about it in OMEC slack before but no response.

**Comment by hyunsun** [comment]
retest this please

**Comment by hyunsun** [comment]
retest this please

**Comment by hyunsun** [comment]
TC1 is still failing.

**Comment by hyunsun** [comment]
retest this please

**Comment by hyunsun** [comment]
retest this please

**Pull request merged**
