### PR TITLE
This commit fixes omec-project#35

### PR DESCRIPTION
**Pull request by wanare-2017**
Old freediameter repo ( https://gerrit.opencord.org/freeDiameter-old ) replace with new omec freediameter repo ( https://github.com/omec-project/freediameter.git ).

### CODE REVIEW

**Comment by omecproject** [comment]
Can one of the admins verify this patch?

**Review by ghost — APPROVED** [review]

**Comment by ghost** [comment]
> Can one of the admins verify this patch?

Done, we should use the freediameter on github.

**Comment by amitinfo2k** [comment]
Can somebody review and integrate this commit ?

**Review by hyunsun — COMMENTED** [review]
+1

**Comment by ghost** [comment]
+1

**Comment by ghost** [comment]
retest this please

**Comment by hyunsun** [comment]
@pingping-lin please merge this

**Pull request merged**
