### PR TITLE
Fix README.txt: wrong link to c3po repo and dir name for hss

### LINKED ISSUE #24: Git repository not found
Hi, I have Ubuntu16.04 and I'm trying to install c3po. 
I'm following instructions in the https://github.com/omec-project/c3po. 
I can't clone into the repository. 
After the command git clone https://gerrit.opencord.org/c3po
I get and error message as 

Cloning into 'c3po'...
fatal: remote error: Git repository not found

Please provide feedback.
Thank you

### PR DESCRIPTION
**Pull request by micpez**
Fix:
- wrong link to c3po repo (gerrit -> github)
- wrong dir in hss instructions (mme -> hss)

resolve #24, #25

### CODE REVIEW

**Comment by micpez** [comment]
retest this please

**Comment by micpez** [comment]
retest this please

**Comment by Sandeep-Sarma** [comment]
LGTM

**Comment by krsna1729** [comment]
@omec-project/c3po-maintainers ping

**Pull request closed without merging**
