### PR TITLE
Fix GCC warnings

### PR DESCRIPTION
**Pull request by krsna1729**
Partly address #7 

Signed-off-by: Saikrishna Edupuganti <saikrishna.edupuganti@intel.com>

### CODE REVIEW

**Comment by omecproject** [comment]
Can one of the admins verify this patch?

**Comment by omecproject** [comment]
Can one of the admins verify this patch?

**Comment by omecproject** [comment]
Can one of the admins verify this patch?

**Comment by omecproject** [comment]
ok to test

**Comment by omecproject** [comment]
ok to test

**Comment by omecproject** [comment]
test this please

**Comment by omecproject** [comment]
retest this please

**Review by somnathchakrabarti — APPROVED** [review]

**Review by somnathchakrabarti — APPROVED** [review]
OK to merge

**Pull request merged**
