### PR TITLE
Create scripts in .ci dir to install HSS and SGX

### PR DESCRIPTION
**Pull request by micpez**
Move install step logic from groovy files to bash scripts in .ci
directory in c3po repo.

### CODE REVIEW

**Comment by micpez** [comment]
retest this please

**Comment by micpez** [comment]
retest this please

**Comment by micpez** [comment]
retest this please

**Comment by micpez** [comment]
retest this please

**Comment by micpez** [comment]
retest this please

**Comment by micpez** [comment]
retest this please

**Comment by micpez** [comment]
retest this please

**Comment by zdw** [comment]
If you want to CI these scripts, I've found [shellcheck](https://github.com/koalaman/shellcheck/) to be very useful for finding edge case issues in shell scripts.

**Comment by micpez** [comment]
> If you want to CI these scripts, I've found [shellcheck](https://github.com/koalaman/shellcheck/) to be very useful for finding edge case issues in shell scripts.

OK for me. As there are other bash scripts in repos, if this will be enabled globally, I guess maintainers should give their OK as well. Meanwhile, I'l do the linting offline.

**Comment by micpez** [comment]
retest this please

**Review by Sandeep-Sarma — COMMENTED** [review]
Looks good except if we can have a naming convention for the install.config files (HSS & SGX).

**Comment by krsna1729** [comment]
@micpez what about TC1 and TC2 files?
https://github.com/omec-project/omec-project-ci/pull/36

**Comment by krsna1729** [comment]
Better to follow same naming/directory convention across NGIC/C3PO/OpenMME repos

**Comment by micpez** [comment]
> 
> 
> @micpez what about TC1 and TC2 files?
> [omec-project/omec-project-ci#36](https://github.com/omec-project/omec-project-ci/pull/36)

Can be done in a following PR.

**Comment by krsna1729** [comment]
@omec-project/c3po-maintainers ping

**Comment by krsna1729** [comment]
@omec-project/c3po-maintainers @micpez If I recollect this is gating forward progress of PRs in queue and any future one that would touch the build/install steps

**Comment by cmaciocco** [comment]
Do we need to add an active maintainer tonthia repo ?
Thanks
Christian

**Comment by krsna1729** [comment]
@cmaciocco we should atleast add @pingping-lin

**Comment by micpez** [comment]
> 
> 
> @omec-project/c3po-maintainers @micpez If I recollect this is gating forward progress of PRs in queue and any future one that would touch the build/install steps

@krsna1729, strictly speaking this is not blocking any PR, it avoids that we need to change also CI/CD scripts for such PRs, by moving as much logic as possible in one single repo.
The goal is to apply such approach to all repos (for openmme there is a similar PR to be checked as well).

**Review by somnathchakrabarti — APPROVED** [review]
approved.

**Pull request merged**
