### PR TITLE
hss log cleanup.

### PR DESCRIPTION
**Pull request by UpadhyayaAnkur**
Dont log hss logs in the file in the K8s environment.

### CODE REVIEW

**Review by thakurajayL — APPROVED** [review]

**Comment by thakurajayL** [comment]
retest fossa

**Comment by thakurajayL** [comment]
retest fossa build

**Comment by thakurajayL** [comment]
retest license please

**Comment by thakurajayL** [comment]
retest licenses build

**Comment by thakurajayL** [comment]
retest FOSSA Verification

**Comment by thakurajayL** [comment]
retest fossa

**Comment by sindack** [comment]
test fossa

**Pull request merged**
